const CMD_GROUP_BASE_INFO_GROUP = 0x00
const CMD_GROUP_LITE_EFFECT_GROUP = 0x20
const CMD_GROUP_SENSOR_INFO_GROUP = 0x40
const CMD_GROUP_MOUSE_BTN_CFG_SET = 0x50
const CMD_GROUP_MOUSE_BTN_CFG_GET = 0x60
const CMD_GROUP_LONG_DATA_GROUP = 0x70
const CMD_GROUP_NOTIFY = 0xe0

export enum EMouseCommand {
	CMD_BASE_GET_PROTOCOL = CMD_GROUP_BASE_INFO_GROUP | 0x2,
	CMD_BASE_GET_BOND_INFO = CMD_GROUP_BASE_INFO_GROUP | 0x3,
	CMD_BASE_GET_DEVICE_STRING = CMD_GROUP_BASE_INFO_GROUP | 0x4,
	CMD_BASE_GET_MOUSE_INFO = CMD_GROUP_BASE_INFO_GROUP | 0x5,
	CMD_BASE_GET_MOUSE_EXT_INFO = CMD_GROUP_BASE_INFO_GROUP | 0x6,
	CMD_BASE_DEV_TIME = CMD_GROUP_BASE_INFO_GROUP | 0xa,
	CMD_BASE_PAIR_BTN = CMD_GROUP_BASE_INFO_GROUP | 0xb,
	CMD_BASE_PROFILE_SWITCH = CMD_GROUP_BASE_INFO_GROUP | 0xe,
	CMD_BASE_SET_DRIVER_CFG_RECOVERY = CMD_GROUP_BASE_INFO_GROUP | 0xf,
	/*************************rgb effect*************************/
	CMD_RGB_GET_LITE_EFFECT_CONFIG_TABLE = CMD_GROUP_LITE_EFFECT_GROUP | 0x0,
	CMD_RGB_GET_LITE_EFFECT_DISPLAY_TABLE = CMD_GROUP_LITE_EFFECT_GROUP | 0x1,
	CMD_RGB_SET_LITE_EFFECT_TABLE_SET = CMD_GROUP_LITE_EFFECT_GROUP | 0x02,
	CMD_RGB_GET_LITE_EFFECT_n_CFG_PARAM = CMD_GROUP_LITE_EFFECT_GROUP | 0x3,
	CMD_RGB_SET_LITE_EFFECT_n_CFG_PARAM = CMD_GROUP_LITE_EFFECT_GROUP | 0x4,
	/*************************mouse information*************************/
	CMD_MOUSE_SET_DPI = CMD_GROUP_SENSOR_INFO_GROUP | 0x00,
	CMD_MOUSE_SET_REPORT_RATE = CMD_GROUP_SENSOR_INFO_GROUP | 0x1,
	CMD_MOUSE_SET_SENSOR_LIFT_CUTOFF_VALUE = CMD_GROUP_SENSOR_INFO_GROUP | 0x2,
	CMD_MOUSE_SET_BTN_DEBOUNCE_TIME = CMD_GROUP_SENSOR_INFO_GROUP | 0x3,
	CMD_MOUSE_SET_DPI_EXT = CMD_GROUP_SENSOR_INFO_GROUP | 0x4,
	/*************************macros & key re-define *************************/
	CMD_MOUSE_BTN_SET_n_CONFIG_VALUE = CMD_GROUP_MOUSE_BTN_CFG_SET | 0x02,
	CMD_MOUSE_BTN_MACROS_SET_n_NAME = CMD_GROUP_MOUSE_BTN_CFG_SET | 0x03,

	CMD_MOUSE_BTN_MACROS_SET_n_CPLT_DATA = CMD_GROUP_MOUSE_BTN_CFG_SET | 0x04,
	CMD_MOUSE_BTN_GET_ALL_CONFIG = CMD_GROUP_MOUSE_BTN_CFG_GET | 0x01,
	CMD_MOUSE_BTN_GET_n_CONFIG = CMD_GROUP_MOUSE_BTN_CFG_GET | 0x02,
	CMD_MOUSE_BTN_MACROS_GET_n_NAME = CMD_GROUP_MOUSE_BTN_CFG_GET | 0x03,
	CMD_MOUSE_BTN_MACROS_GET_n_CPLT_DATA = CMD_GROUP_MOUSE_BTN_CFG_GET | 0x04,
	//mouse & button profile
	CMD_MOUSE_PROFILE_n_SET = CMD_GROUP_MOUSE_BTN_CFG_SET | 0x0F,
	CMD_MOUSE_PROFILE_n_GET = CMD_GROUP_MOUSE_BTN_CFG_GET | 0x0F,
	/*Long data*/
	CMD_LDATA_RTX = CMD_GROUP_LONG_DATA_GROUP | 0x1,
	CMD_LDATA_FLOW_CONTROL = CMD_GROUP_LONG_DATA_GROUP | 0x2,
	/*Mouse Status */
	CMD_MOUSE_ELE_MODE = CMD_GROUP_NOTIFY | 0x2
}
