export enum EMouseKeycodeDefault {
	USB_USAGE_NO_EVENT = 0,
	USB_USAGE_ROLLOVER = 1,
	USB_USAGE_POST_FAIL = 2,
	USB_USAGE_UNDEFINED_ERROR = 3,
	KC_A = 4,
	KC_B = 5,
	KC_C = 6,
	KC_D = 7,
	KC_E = 8,
	KC_F = 9,
	KC_G = 10,
	KC_H = 11,
	KC_I = 12,
	KC_J = 13,
	KC_K = 14,
	KC_L = 15,
	KC_M = 16,
	KC_N = 17,
	KC_O = 18,
	KC_P = 19,
	KC_Q = 20,
	KC_R = 21,
	KC_S = 22,
	KC_T = 23,
	KC_U = 24,
	KC_V = 25,
	KC_W = 26,
	KC_X = 27,
	KC_Y = 28,
	KC_Z = 29,
	KC_1 = 30,
	KC_2 = 31,
	KC_3 = 32,
	KC_4 = 33,
	KC_5 = 34,
	KC_6 = 35,
	KC_7 = 36,
	KC_8 = 37,
	KC_9 = 38,
	KC_0 = 39,
	KC_ENT = 40,
	KC_ESC = 41,
	USB_USAGE_BACKSPACE = 42,
	USB_USAGE_TAB = 43,
	KC_SPC = 44,
	KC_MINS = 45,
	KC_EQL = 46,
	KC_LBRC = 47,
	KC_RBRC = 48,
	KC_BSLS = 49,
	USB_USAGE_NON_US_HASH = 50,
	KC_SCLN = 51,
	KC_QUOT = 52,
	KC_GRV = 53,
	KC_COMM = 54,
	KC_DOT = 55,
	KC_SLSH = 56,
	KC_CAPS = 57,
	KC_F1 = 58,
	KC_F2 = 59,
	KC_F3 = 60,
	KC_F4 = 61,
	KC_F5 = 62,
	KC_F6 = 63,
	KC_F7 = 64,
	KC_F8 = 65,
	KC_F9 = 66,
	KC_F10 = 67,
	KC_F11 = 68,
	KC_F12 = 69,
	KC_PSCR = 70,
	KC_SLCK = 71,
	KC_PAUS = 72,
	KC_INS = 73,
	KC_HOME = 74,
	KC_PGUP = 75,
	KC_DEL = 76,
	KC_END = 77,
	KC_PGDN = 78,
	KC_RGHT = 79,
	KC_LEFT = 80,
	KC_DOWN = 81,
	KC_UP = 82,
	KC_NLCK = 83,
	KC_PSLS = 84,
	KC_PAST = 85,
	KC_PMNS = 86,
	KC_PPLS = 87,
	KC_PENT = 88,
	KC_P1 = 89,
	KC_P2 = 90,
	KC_P3 = 91,
	KC_P4 = 92,
	KC_P5 = 93,
	KC_P6 = 94,
	KC_P7 = 95,
	KC_P8 = 96,
	KC_P9 = 97,
	KC_P0 = 98,
	KC_PDOT = 99,
	USB_USAGE_NON_US_BACK_SLASH = 100,
	USB_USAGE_APPLICATION = 101,
	USB_USAGE_POWER = 102,
	USB_USAGE_KP_EQUAL = 103,
	KC_F13 = 104,
	KC_F14 = 105,
	KC_F15 = 106,
	KC_F16 = 107,
	KC_F17 = 108,
	KC_F18 = 109,
	KC_F19 = 110,
	KC_F20 = 111,
	KC_F21 = 112,
	KC_F22 = 113,
	KC_F23 = 114,
	KC_F24 = 115,
	USB_USAGE_EXECUTE = 116,
	KC_HELP = 117,
	KC_APP = 118,
	USB_USAGE_SELECT = 119,
	USB_USAGE_STOP = 120,
	USB_USAGE_AGAIN = 121,
	USB_USAGE_UNDO = 122,
	USB_USAGE_CUT = 123,
	USB_USAGE_COPY = 124,
	USB_USAGE_PASTE = 125,
	USB_USAGE_FIND = 126,
	KC_MUTE = 127,
	KC_VOLU = 128,
	KC_VOLD = 129,
	USB_USAGE_LOCKING_CAPS_LOCK = 130,
	USB_USAGE_LOCKING_NUM_LOCK = 131,
	USB_USAGE_LOCKING_SCROLL_LOCK = 132,
	KC_PCMM = 133,
	KC_PEQL = 134,
	USB_USAGE_INTL_1 = 135,
	USB_USAGE_INTL_2 = 136,
	USB_USAGE_INTL_3 = 137,
	USB_USAGE_INTL_4 = 138,
	USB_USAGE_INTL_5 = 139,
	USB_USAGE_INTL_6 = 140,
	USB_USAGE_INTL_7 = 141,
	USB_USAGE_INTL_8 = 142,
	USB_USAGE_INTL_9 = 143,
	USB_USAGE_LANG_1 = 144,
	USB_USAGE_LANG_2 = 145,
	USB_USAGE_LANG_3 = 146,
	USB_USAGE_LANG_4 = 147,
	USB_USAGE_LANG_5 = 148,
	USB_USAGE_LANG_6 = 149,
	USB_USAGE_LANG_7 = 150,
	USB_USAGE_LANG_8 = 151,
	USB_USAGE_LANG_9 = 152,
	USB_USAGE_ALT_ERASE = 153,
	USB_USAGE_SYS_REQ = 154,
	USB_USAGE_CANCEL = 155,
	USB_USAGE_CLEAR = 156,
	USB_USAGE_PRIOR = 157,
	USB_USAGE_RETURN = 158,
	USB_USAGE_SEPARATOR = 159,
	USB_USAGE_OUT = 160,
	USB_USAGE_OPER = 161,
	USB_USAGE_CLEAR_AGAIN = 162,
	USB_USAGE_CRSEL = 163,
	USB_USAGE_EXSEL = 164,
	USB_USAGE_KP_00 = 176,
	USB_USAGE_KP_000 = 177,
	USB_USAGE_THOUSANDS_SEPERATOR = 178,
	USB_USAGE_DECIMAL_SEPERATOR = 179,
	USB_USAGE_CURRENCY_UNIT = 180,
	USB_USAGE_CURRENCY_SUB_UNIT = 181,
	USB_USAGE_KP_LEFT_PAREN = 182,
	USB_USAGE_KP_RIGHT_PAREN = 183,
	USB_USAGE_KP_LEFT_CURLY_BRACE = 184,	//[
	USB_USAGE_KP_RIGHT_CURLY_BRACE = 185,	//]
	KC_TAB = 186,
	KC_BSPC = 187,
	USB_USAGE_KP_A = 188,
	USB_USAGE_KP_B = 189,
	USB_USAGE_KP_C = 190,
	USB_USAGE_KP_D = 191,
	USB_USAGE_KP_E = 192,
	USB_USAGE_KP_F = 193,
	USB_USAGE_KP_XOR = 194,
	USB_USAGE_KP_CARET = 195,
	USB_USAGE_KP_PERCENT = 196,
	USB_USAGE_KP_LESS_THAN = 197,
	USB_USAGE_KP_GREATER_THAN = 198,
	USB_USAGE_KP_AMPERSAND = 199,
	USB_USAGE_KP_DOUBLE_AMPERSAND = 200,
	USB_USAGE_KP_VERTICAL_BAR = 201,
	USB_USAGE_KP_DOUBLE_VERTICAL_BAR = 202,
	USB_USAGE_KP_COLON = 203,
	USB_USAGE_KP_HASH = 204,
	USB_USAGE_KP_SPACE = 205,
	USB_USAGE_KP_AT = 206,
	USB_USAGE_KP_EXCLAMATION = 207,
	USB_USAGE_KP_MEM_STORE = 208,
	USB_USAGE_KP_MEM_RECALL = 209,
	USB_USAGE_KP_MEM_CLEAR = 210,
	USB_USAGE_KP_MEM_ADD = 211,
	USB_USAGE_KP_MEM_SUBTRACT = 212,
	USB_USAGE_KP_MEM_MULTIPLY = 213,
	USB_USAGE_KP_MEM_DIVIDE = 214,
	USB_USAGE_KP_PLUS_MINUS = 215,
	USB_USAGE_KP_CLEAR = 216,
	USB_USAGE_KP_CLEAR_ENTRY = 217,
	USB_USAGE_KP_BINARY = 218,
	USB_USAGE_KP_OCTAL = 219,
	USB_USAGE_KP_DECIMAL = 220,
	USB_USAGE_KP_HEX = 221,
	KC_LCTL = 224,
	KC_LSFT = 225,
	KC_LALT = 226,
	KC_LGUI = 227,
	KC_RCTL = 228,
	KC_RSFT = 229,
	KC_RALT = 230,
	KC_RGUI = 231
}

export const EvtToMouseKeyByte:any = {
	Digit1: EMouseKeycodeDefault.KC_1,
	Digit2: EMouseKeycodeDefault.KC_2,
	Digit3: EMouseKeycodeDefault.KC_3,
	Digit4: EMouseKeycodeDefault.KC_4,
	Digit5: EMouseKeycodeDefault.KC_5,
	Digit6: EMouseKeycodeDefault.KC_6,
	Digit7: EMouseKeycodeDefault.KC_7,
	Digit8: EMouseKeycodeDefault.KC_8,
	Digit9: EMouseKeycodeDefault.KC_9,
	Digit0: EMouseKeycodeDefault.KC_0,
	KeyA: EMouseKeycodeDefault.KC_A,
	KeyB: EMouseKeycodeDefault.KC_B,
	KeyC: EMouseKeycodeDefault.KC_C,
	KeyD: EMouseKeycodeDefault.KC_D,
	KeyE: EMouseKeycodeDefault.KC_E,
	KeyF: EMouseKeycodeDefault.KC_F,
	KeyG: EMouseKeycodeDefault.KC_G,
	KeyH: EMouseKeycodeDefault.KC_H,
	KeyI: EMouseKeycodeDefault.KC_I,
	KeyJ: EMouseKeycodeDefault.KC_J,
	KeyK: EMouseKeycodeDefault.KC_K,
	KeyL: EMouseKeycodeDefault.KC_L,
	KeyM: EMouseKeycodeDefault.KC_M,
	KeyN: EMouseKeycodeDefault.KC_N,
	KeyO: EMouseKeycodeDefault.KC_O,
	KeyP: EMouseKeycodeDefault.KC_P,
	KeyQ: EMouseKeycodeDefault.KC_Q,
	KeyR: EMouseKeycodeDefault.KC_R,
	KeyS: EMouseKeycodeDefault.KC_S,
	KeyT: EMouseKeycodeDefault.KC_T,
	KeyU: EMouseKeycodeDefault.KC_U,
	KeyV: EMouseKeycodeDefault.KC_V,
	KeyW: EMouseKeycodeDefault.KC_W,
	KeyX: EMouseKeycodeDefault.KC_X,
	KeyY: EMouseKeycodeDefault.KC_Y,
	KeyZ: EMouseKeycodeDefault.KC_Z,
	Comma: EMouseKeycodeDefault.KC_COMM,
	Period: EMouseKeycodeDefault.KC_DOT,
	Semicolon: EMouseKeycodeDefault.KC_SCLN,
	Quote: EMouseKeycodeDefault.KC_QUOT,
	BracketLeft: EMouseKeycodeDefault.KC_LBRC,
	BracketRight: EMouseKeycodeDefault.KC_RBRC,
	Backspace: EMouseKeycodeDefault.USB_USAGE_BACKSPACE,
	Backquote: EMouseKeycodeDefault.KC_GRV,
	Slash: EMouseKeycodeDefault.KC_SLSH,
	Backslash: EMouseKeycodeDefault.KC_BSLS,
	Minus: EMouseKeycodeDefault.KC_MINS,
	Equal: EMouseKeycodeDefault.KC_EQL,
	// IntlRo: EMouseKeycodeDefault.KC_RO,
	// IntlYen: EMouseKeycodeDefault.KC_JYEN,
	AltLeft: EMouseKeycodeDefault.KC_LALT,
	AltRight: EMouseKeycodeDefault.KC_RALT,
	CapsLock: EMouseKeycodeDefault.KC_CAPS,
	ControlLeft: EMouseKeycodeDefault.KC_LCTL,
	ControlRight: EMouseKeycodeDefault.KC_RCTL,
	MetaLeft: EMouseKeycodeDefault.KC_LGUI,
	MetaRight: EMouseKeycodeDefault.KC_RGUI,
	OSLeft: EMouseKeycodeDefault.KC_LGUI,
	OSRight: EMouseKeycodeDefault.KC_RGUI,
	ShiftLeft: EMouseKeycodeDefault.KC_LSFT,
	ShiftRight: EMouseKeycodeDefault.KC_RSFT,
	ContextMenu: EMouseKeycodeDefault.KC_APP,
	Enter: EMouseKeycodeDefault.KC_ENT,
	Space: EMouseKeycodeDefault.KC_SPC,
	Tab: EMouseKeycodeDefault.USB_USAGE_TAB,
	Delete: EMouseKeycodeDefault.KC_DEL,
	End: EMouseKeycodeDefault.KC_END,
	Help: EMouseKeycodeDefault.KC_HELP,
	Home: EMouseKeycodeDefault.KC_HOME,
	Insert: EMouseKeycodeDefault.KC_INS,
	PageDown: EMouseKeycodeDefault.KC_PGDN,
	PageUp: EMouseKeycodeDefault.KC_PGUP,
	ArrowDown: EMouseKeycodeDefault.KC_DOWN,
	ArrowLeft: EMouseKeycodeDefault.KC_LEFT,
	ArrowRight: EMouseKeycodeDefault.KC_RGHT,
	ArrowUp: EMouseKeycodeDefault.KC_UP,
	Escape: EMouseKeycodeDefault.KC_ESC,
	PrintScreen: EMouseKeycodeDefault.KC_PSCR,
	ScrollLock: EMouseKeycodeDefault.KC_SLCK,
	AudioVolumeUp: EMouseKeycodeDefault.KC_VOLU,
	AudioVolumeDown: EMouseKeycodeDefault.KC_VOLD,
	AudioVolumeMute: EMouseKeycodeDefault.KC_MUTE,
	Pause: EMouseKeycodeDefault.KC_PAUS,
	F1: EMouseKeycodeDefault.KC_F1,
	F2: EMouseKeycodeDefault.KC_F2,
	F3: EMouseKeycodeDefault.KC_F3,
	F4: EMouseKeycodeDefault.KC_F4,
	F5: EMouseKeycodeDefault.KC_F5,
	F6: EMouseKeycodeDefault.KC_F6,
	F7: EMouseKeycodeDefault.KC_F7,
	F8: EMouseKeycodeDefault.KC_F8,
	F9: EMouseKeycodeDefault.KC_F9,
	F10: EMouseKeycodeDefault.KC_F10,
	F11: EMouseKeycodeDefault.KC_F11,
	F12: EMouseKeycodeDefault.KC_F12,
	F13: EMouseKeycodeDefault.KC_F13,
	F14: EMouseKeycodeDefault.KC_F14,
	F15: EMouseKeycodeDefault.KC_F15,
	F16: EMouseKeycodeDefault.KC_F16,
	F17: EMouseKeycodeDefault.KC_F17,
	F18: EMouseKeycodeDefault.KC_F18,
	F19: EMouseKeycodeDefault.KC_F19,
	F20: EMouseKeycodeDefault.KC_F20,
	F21: EMouseKeycodeDefault.KC_F21,
	F22: EMouseKeycodeDefault.KC_F22,
	F23: EMouseKeycodeDefault.KC_F23,
	F24: EMouseKeycodeDefault.KC_F24,
	NumLock: EMouseKeycodeDefault.KC_NLCK,
	Numpad0: EMouseKeycodeDefault.KC_P0,
	Numpad1: EMouseKeycodeDefault.KC_P1,
	Numpad2: EMouseKeycodeDefault.KC_P2,
	Numpad3: EMouseKeycodeDefault.KC_P3,
	Numpad4: EMouseKeycodeDefault.KC_P4,
	Numpad5: EMouseKeycodeDefault.KC_P5,
	Numpad6: EMouseKeycodeDefault.KC_P6,
	Numpad7: EMouseKeycodeDefault.KC_P7,
	Numpad8: EMouseKeycodeDefault.KC_P8,
	Numpad9: EMouseKeycodeDefault.KC_P9,
	NumpadAdd: EMouseKeycodeDefault.KC_PPLS,
	NumpadComma: EMouseKeycodeDefault.KC_COMM,
	NumpadDecimal: EMouseKeycodeDefault.KC_PDOT,
	NumpadDivide: EMouseKeycodeDefault.KC_PSLS,
	NumpadEnter: EMouseKeycodeDefault.KC_PENT,
	NumpadEqual: EMouseKeycodeDefault.KC_PEQL,
	NumpadMultiply: EMouseKeycodeDefault.KC_PAST,
	NumpadSubtract: EMouseKeycodeDefault.KC_PMNS,
};
