export enum EKeyboardCommand {
	GET_PROTOCOL_VERSION = 0x01,
	GET_KEYBOARD_VALUE = 0x02,
	SET_KEYBOARD_VALUE = 0x03,
	DYNAMIC_KEYMAP_GET_KEYCODE = 0x04,
	DYNAMIC_KEYMAP_SET_KEYCODE = 0x05,
	DYNAMIC_KEYMAP_CLEAR_ALL = 0x06,
	CUSTOM_MENU_SET_VALUE = 0x07,
	CUSTOM_MENU_GET_VALUE = 0x08,
	CUSTOM_MENU_SAVE = 0x09,
	EEPROM_RESET = 0x0a,
	BOOTLOADER_JUMP = 0x0b,
	DYNAMIC_KEYMAP_MACRO_GET_COUNT = 0x0c,
	DYNAMIC_KEYMAP_MACRO_GET_BUFFER_SIZE = 0x0d,
	DYNAMIC_KEYMAP_MACRO_GET_BUFFER = 0x0e,
	DYNAMIC_KEYMAP_MACRO_SET_BUFFER = 0x0f,
	DYNAMIC_KEYMAP_MACRO_RESET = 0x10,
	DYNAMIC_KEYMAP_GET_LAYER_COUNT = 0x11,
	DYNAMIC_KEYMAP_GET_BUFFER = 0x12,
	DYNAMIC_KEYMAP_SET_BUFFER = 0x13,
	DYNAMIC_KEYMAP_GET_ENCODER = 0x14,
	DYNAMIC_KEYMAP_SET_ENCODER = 0x15,
	// DEPRECATED:
	BACKLIGHT_CONFIG_SET_VALUE = 0x07,
	BACKLIGHT_CONFIG_GET_VALUE = 0x08,
	BACKLIGHT_CONFIG_SAVE = 0x09,

	KC_GET_PROTOCOL_VERSION = 0xA0,
	KC_FIRMWARE_VERSION = 0xA1,
	KC_GET_SUPPORT_FEATURE = 0xA2,
	KC_GET_CURRENT_LAYER = 0xA3,
	KC_DEBOUNCE = 0xA7,
	KC_RGB = 0xA8,
	KC_HE = 0xA9
}

export enum EHECommand {
	AMC_GET_VERSION = 0x01,
	AMC_GET_PROFILES_INFO = 0x10,
	AMC_SELECT_PROFILE,
	AMC_GET_PROFILE_BUFFER,
	AMC_SET_PROFILE_NAME,
	AMC_SET_TRAVAL,
	AMC_SET_ADVANCE_MODE,
	AMC_SET_ACT_ON_AXIS,
	AMC_GET_CURVE = 0x20,
	AMC_SET_CURVE,
	AMC_GET_REALTIME_TRAVEL = 0x30,
	AMC_CALIBRATE = 0x40,
	AMC_GET_CALIBRATE_STATE,
	AMC_GET_CALIBRATED_VALUE,
	AMC_CLEAR_PROFILE_BUFFER = 0x1E,
	AMC_SAVE_PROFILE_BUFFER = 0x1F,
}

export enum EBluetoothState {
	Init,
	Pending,
}

export enum EBluetooth {
	PacketType_Header = 0xAA,
	PacketType_Send_NoAck = 0x55,
	PacketType_Send_Ack = 0x56
}

export type EKeyboardCommandIndexing = keyof typeof EKeyboardCommand
